# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [4]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Javier/anaconda3/Library/include
    lib directory: C:/Users/Javier/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [14]:
# default random values
a = np.random.random((2,3,5))
print(a)

print("######################################################################################")
# randn
a = np.random.randn(2,3,5)
print(a)

print("######################################################################################")
# 10 -> values from 0 to n integers, can be
n = 10
a = np.random.randint(n, size = (2,3,5))
print(a)


[[[0.12858143 0.08300808 0.21156178 0.67405125 0.33598444]
  [0.95439102 0.50143789 0.38884112 0.92389194 0.26009272]
  [0.93911732 0.58101789 0.4468634  0.22658693 0.12564277]]

 [[0.28364709 0.46829597 0.51814797 0.68542598 0.00258822]
  [0.50047984 0.83786156 0.55044554 0.72467446 0.52820354]
  [0.81060757 0.77539223 0.28223258 0.60473505 0.43372726]]]
######################################################################################
[[[-0.9927876  -0.63177578  0.43254557  1.83189175 -0.24065505]
  [-0.18090518 -0.3306414   0.90054184  0.24208984  0.86906712]
  [ 1.12270392 -0.13394138  0.79429594 -0.42029179  1.79815274]]

 [[ 0.51431129 -2.60609466  0.55375818  0.59716498 -1.01449208]
  [-1.06568875  0.59574976 -2.74097747 -1.2956727  -0.5502311 ]
  [-0.71196069 -0.78435984  0.16480389 -0.59120202  0.1002567 ]]]
######################################################################################
[[[6 5 0 0 6]
  [5 0 4 9 4]
  [4 5 5 5 3]]

 [[3 4 6 6 0]
  [3 3 1 5 6]
  [1 8 0


### 4. Print a.


In [15]:
print(a)


[[[6 5 0 0 6]
  [5 0 4 9 4]
  [4 5 5 5 3]]

 [[3 4 6 6 0]
  [3 3 1 5 6]
  [1 8 0 9 5]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [18]:
b = np.ones((5,2,3))



### 6. Print b.


In [19]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [20]:
same_size = a.size == b.size
same_size

True


### 8. Are you able to add a and b? Why or why not?


In [21]:
### [your code here]
result_sum = a + b

## cannot be added because they have different shapes. It does not matter that they have same size


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [29]:
### [your code here]
print(b.shape)
c = np.transpose(b, (1,2,0))
print(c.shape)
print(a.shape)


(5, 2, 3)
(2, 3, 5)
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [31]:
### [your code here]

d = sum_arrays = a + c
d

array([[[ 7.,  6.,  1.,  1.,  7.],
        [ 6.,  1.,  5., 10.,  5.],
        [ 5.,  6.,  6.,  6.,  4.]],

       [[ 4.,  5.,  7.,  7.,  1.],
        [ 4.,  4.,  2.,  6.,  7.],
        [ 2.,  9.,  1., 10.,  6.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [32]:
### [your code here]
print(a)

print(d)

# As we have an array with random values and another filled with 1s, when we add one to the other, it add each position because is the same,
# For example position 0,0,0 of a is 6 and added to 1 is 7, which is the value of the position 0,0,0 in D



[[[6 5 0 0 6]
  [5 0 4 9 4]
  [4 5 5 5 3]]

 [[3 4 6 6 0]
  [3 3 1 5 6]
  [1 8 0 9 5]]]
[[[ 7.  6.  1.  1.  7.]
  [ 6.  1.  5. 10.  5.]
  [ 5.  6.  6.  6.  4.]]

 [[ 4.  5.  7.  7.  1.]
  [ 4.  4.  2.  6.  7.]
  [ 2.  9.  1. 10.  6.]]]



### 12. Multiply a and c. Assign the result to e.


In [34]:
### [your code here]
e = a*c
e

array([[[6., 5., 0., 0., 6.],
        [5., 0., 4., 9., 4.],
        [4., 5., 5., 5., 3.]],

       [[3., 4., 6., 6., 0.],
        [3., 3., 1., 5., 6.],
        [1., 8., 0., 9., 5.]]])



### 13. Does e equal to a? Why or why not?


In [35]:
### [your code here]
print(e == a)

## Both are equal, if you are comparing, size, values, shape and the rest of the properties of the array


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [52]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [55]:
### Los valores al imprimirlo son los que estaban en memoria antes
f = np.empty((2,3,5))
print(f)

[[[6. 5. 0. 0. 6.]
  [5. 0. 4. 9. 4.]
  [4. 5. 5. 5. 3.]]

 [[3. 4. 6. 6. 0.]
  [3. 3. 1. 5. 6.]
  [1. 8. 0. 9. 5.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [56]:
### [your code here]

d_pos = 0
for matrix in d:
    matrix_pos = 0
    for vector in matrix:
        vector_pos = 0
        for value in vector:
            if value > d_min and value < d_mean:
                f[d_pos, matrix_pos, vector_pos] = 25
            elif value >= d_mean and value < d_max:
                f[d_pos, matrix_pos, vector_pos] = 75
            elif value == d_mean:
                f[d_pos, matrix_pos, vector_pos] = 50
            elif value == d_min:
                f[d_pos, matrix_pos, vector_pos] = 0
            elif value == d_max:
                f[d_pos, matrix_pos, vector_pos] = 100

            vector_pos += 1
        matrix_pos += 1
    d_pos += 1

print(f)
                
            

[[[ 75.  75.   0.   0.  75.]
  [ 75.   0.  25. 100.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  75.   0.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.   0. 100.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [58]:
### [your code here]
print(d)
print("######################################################################################")
print(f)

[[[ 7.  6.  1.  1.  7.]
  [ 6.  1.  5. 10.  5.]
  [ 5.  6.  6.  6.  4.]]

 [[ 4.  5.  7.  7.  1.]
  [ 4.  4.  2.  6.  7.]
  [ 2.  9.  1. 10.  6.]]]
######################################################################################
[[[ 75.  75.   0.   0.  75.]
  [ 75.   0.  25. 100.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  75.   0.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.   0. 100.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [60]:
### [your code here]
g = np.empty((2,3,5), dtype=str)
print(g)

d_pos = 0
for matrix in d:
    matrix_pos = 0
    for vector in matrix:
        vector_pos = 0
        for value in vector:
            if value > d_min and value < d_mean:
                g[d_pos, matrix_pos, vector_pos] = "B"
            elif value >= d_mean and value < d_max:
                g[d_pos, matrix_pos, vector_pos] = "D"
            elif value == d_mean:
                g[d_pos, matrix_pos, vector_pos] = "C"
            elif value == d_min:
                g[d_pos, matrix_pos, vector_pos] = "A"
            elif value == d_max:
                g[d_pos, matrix_pos, vector_pos] = "E"

            vector_pos += 1
        matrix_pos += 1
    d_pos += 1

print(g)
                
            

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
[[['D' 'D' 'A' 'A' 'D']
  ['D' 'A' 'B' 'E' 'B']
  ['B' 'D' 'D' 'D' 'B']]

 [['B' 'B' 'D' 'D' 'A']
  ['B' 'B' 'B' 'D' 'D']
  ['B' 'D' 'A' 'E' 'D']]]
